name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
  
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            lucasdantas123/kube-new:latest
            lucasdantas123/kube-new:${{github.run_number}}
          
  CD:
    runs-on: ubuntu-lates
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes Set Context
      - uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.k8s_CONFIG}}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          images: lucasdantas123/kube-new:${{github.run_number}}
          manifests: |
            k8s/deploymnent.yaml
